485DIR = ../rpiuart/
ModDIR = modules/
CC = gcc -L/usr/local/lib -L/usr/local/include -lIPC
CFLAGS = -Wall
SOURCES = main.c
MODULES = module.c super_module.c gui_module.c
RS485 = packetformatter.c io.c devicehandler.c datahandler.c
OBJECTS = $(SOURCES:.c=.o) $(addprefix $(ModDIR),$(MODULES:.c=.o)) $(addprefix $(485DIR),$(RS485:.c=.o))
EXECUTABLE = main

$(EXECUTABLE):	$(OBJECTS)

clean:
	rm -f $(EXECUTABLE) $(OBJECTS)
